---
title: "Ambient-BD Data Sheet"
format:
 pdf:
  include-in-header: style.tex
execute:
 echo: false
---

::: {.raw-latex}
\vspace{-2em}
\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}
:::

- Date range: 01/09/2025 to 27/09/2025
- Participant ID: ABD001

::: {.raw-latex}
\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}
\vspace{2em}
:::

```{r}
somnofy_file <- "/media/Store/Daniel/Ambient-BD/Data/Data_sheet_test_input/WP4_test/ABD001_SOM-Sess_2025-11-17.csv"
somnofy <- nocturn::load_sessions(somnofy_file) |>
  AmbientDataSheet::clean_data() |>
  nocturn::filter_by_night_range("2025-09-01", "2025-09-27")

ema_file <- "/media/Store/Daniel/Ambient-BD/Data/Data_sheet_test_input/WP4_test/ABD001_PROM-EMA_module_bfef9dv80oupx78m_20251112.csv"

ema <- nocturn::load_sessions(ema_file) |>
  nocturn::set_colnames(AmbientDataSheet::ema_colnames)
ema_col <- nocturn::get_colnames(ema)
ema[[ema_col$sleep_onset_latency]] <- ema[[ema_col$sleep_onset_latency]] * 60 # minutes to seconds
ema <- nocturn::clean_sessions(ema) |>
  AmbientDataSheet::clean_data()

axivity_file <- "/media/Store/Daniel/Ambient-BD/Data/Data_sheet_test_input/WP4_test/Fake_GGIR_part4.csv"

axivity <- nocturn::load_sessions(axivity_file) |>
  AmbientDataSheet::clean_data()
```

```{r child="block_somnofy_only.qmd"}
```

```{r child="block_burst.qmd"}
```